# Site settings
title: Consulting
subtitle: by Moodule
description: >- # this means to ignore newlines until "baseurl:"
  A responsive site template designed by <a href="david.mougeolle@moodule.net">DM</a> for <a href="https://github.com/moodule">MOODULE</a>.<br />
  It’s responsive, built on HTML5/CSS3, and entirely free<br />
  under the <a href="https://github.com/moodule/jekyll-theme-consulting/blob/master/LICENSE">Creative Commons license</a>.

# Contact information
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555
email: youremailaddress@gmail.com

# Social settings
500px_url: https://github.com/moodule
facebook_url: https://github.com/moodule
github_url: https://github.com/moodule
gitlab_url: https://github.com/moodule
instagram_url: https://github.com/moodule
linkedin_url: https://github.com/moodule
medium_url: https://github.com/moodule
pinterest_url: https://github.com/moodule
slack_url: https://github.com/moodule
snapchat_url: https://github.com/moodule
twitter_url: https://github.com/moodule

# Optional elements
logo_url: /assets/images/logo.svg
favicon_url: /assets/images/favicon.ico
legal_terms_url: /legal-terms
privacy_policy_url: /privacy-policy

# Privacy notice
hosting_third_party: github

# Collections
collections:
  redirects:
    output: true
    permalink: /:path/

# Default settings
defaults:
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
  -
    scope:
      path: ""
    values:
      menu: default
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"

# Build settings
permalink: pretty
markdown: kramdown
sass:
  style: compressed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moodule.github.io/jekyll-theme-consulting" # the base hostname & protocol for your site, e.g. http://example.com
author: David Mougeolle
copyright_holder: Untitled

# Exclude from processing
