# Site settings
title: Consulting
subtitle: by apehex
description: >- # this means to ignore newlines until "baseurl:"
  A responsive site template designed by <a href="apehex@protonmail.com">DM</a> for <a href="https://github.com/apehex">apehex</a>.<br />
  Itâ€™s responsive, built on HTML5/CSS3, and entirely free<br />
  under the <a href="https://github.com/apehex/jekyll-theme-consulting/blob/master/LICENSE">Creative Commons license</a>.

# Contact information
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555
email: youremailaddress@gmail.com

# Social settings
500px_url: https://github.com/apehex
facebook_url: https://github.com/apehex
github_url: https://github.com/apehex
gitlab_url: https://github.com/apehex
instagram_url: https://github.com/apehex
linkedin_url: https://github.com/apehex
medium_url: https://github.com/apehex
pinterest_url: https://github.com/apehex
slack_url: https://github.com/apehex
snapchat_url: https://github.com/apehex
twitter_url: https://github.com/apehex

# Optional elements
logo_url: /assets/images/logo.svg
favicon_url: /assets/images/favicon.ico
legal_terms_url: /legal-terms
privacy_policy_url: /privacy-policy

# Collections
collections:
  redirects:
    output: true
    permalink: /:path/

# Default settings
defaults:
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
  -
    scope:
      path: ""
    values:
      menu: default

# Build settings
permalink: pretty
markdown: kramdown
sass:
  style: compressed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: apehex
copyright_holder: Untitled

# Exclude from processing
